### ISSUE TITLE
Great work. Any plan for AVTP?

### ISSUE THREAD

**Issue by sigusr1** [xl4-shiro/excelfore-gptp#1]
As I know, gPTP is for commercial use and source code is not release to customer before.
Very glad to see you open sourced it. 
By the way, will you open AVTP in the near future?

**Comment by xl4-shiro** [comment]
Thanks for the message.

We basically want to open more source codes, and the avtp code could be the next one.
But I can't promise when it will happen, the end of this year could be possible at the earliest.
