### ISSUE TITLE
10Mbps speed support

### ISSUE THREAD

**Issue by duribee** [xl4-shiro/excelfore-gptp#14]
Hello,

Is there any reason why speed above 100 Mbps is needed for gptp2d to run? I was trying to execute the stack using a 10Mbps interface but the following warning was displayed:

WRN:gptp:!!! Full duplex link with Speed above 100 Mbps needed for gptp to run !!!

Also, is there any way to pass integer arrays using the configuration file? For example if we want to configure a CONF_LOG_SYNC_INTERVAL independently for every port, what would be your recomendation?

Best regards,
Daniel

**Comment by xl4-shiro** [comment]
100Mbps comes from 802.1AS standard.

The config doesn't have an array setting, CONF_PTP_PORT_ENABLED is using
comma separated values as a string.
For such needs, we use xl4unipac which is also in our github.

**Comment by duribee** [comment]
I've been trying to find the requirements of link speeds of 100Mbps or more at the 802.1AS-2020 standard but I do not find it. Could you please point me to the section where it is defined?

Is there any specific reason that could prevent the gptp2d stack to work at 10Mbps? could it be possible to remove this condition and the allow also 10Mbps speed?

if(ed->speed<100 || ed->duplex!=1){
UB_LOG(UBL_WARN,"!!! Full duplex link with "
		"Speed above 100 Mbps needed for gptp to run !!!\n");
}

Any advice is appreciated.

Thank you!

**Comment by xl4-shiro** [comment]
I don't remember the exact place to find the minimum 100Mbps condition.
It might come to achieve meanLinkDelayThresh.

If the meanLinkDelayThresh was not needed to be cared for, it might be okay
to remove the condition.

**Comment by duribee** [comment]
Thank you for the quick support.
