### ISSUE TITLE
Question: What is the pedigree and verification approach of this source code?

### ISSUE THREAD

**Issue by schaveyt** [xl4-shiro/excelfore-gptp#2]
Thank you very much for open sourcing this source code!  I am not too familiar with excelfore and their products.

1. Could you tell me the history/pedigree/where-it-has-been-used?
1. Could you tell me how this software was verified to confirm is compliance to:
   1. 802.1AS
   1. 802.1AS-REV part

**Comment by xl4-shiro** [comment]
Regarding the first question, please look at [our web site.](https://excelfore.com/in-vehicle-networks/)  gPTP is a key technology of AVB/TSN, and we have already used in many commercial projects.

Regarding the verification, unit tests and some methods of testing are mentioned in the documents included in the source tree.
More than that, we have our internal test procedure to cover many parts of the standard.  And we add some project specific testings to cover as many as possible use cases.
Such testing detail is beyond this open sourcing effort, and won't be disclosed.

**Comment by schaveyt** [comment]
Thank you. Im interested in evaluating this for future use. Will continue to dig.
