### ISSUE TITLE
Question about how to run the stack with SW timestamp

### ISSUE THREAD

**Issue by bryce22** [xl4-shiro/excelfore-gptp#4]
I'm new for excelfore's  open source gPTP stack and we want to evaluate the performance for further cooperate possibility.

I mounted a virtual Linux system on my computer and the NIC can't support HW timestamp, as the ethtool -T command result in the picture below.

![NIC without HW timestamp function](https://user-images.githubusercontent.com/88758350/129133521-ecd977b4-b363-4b3d-9946-3fbbf9d8d796.JPG)

NIC ens39 in Linux has been mapped the a real NIC of my computer. And I can capture the gPTP messages when I applied ptp4l of linuxptp stack. So I created a virtual network port as the guidance. The virtual network port I created is ens39:0.
![virtual NIC](https://user-images.githubusercontent.com/88758350/129134645-2409982a-e05c-49b4-9fba-964190da48e2.jpg)

Then I run the stack with command: gptp2d -d ens39:0,ens39. And there is an error "ERR:gptp:gptpnet_init:ptp device is needed for at least one network device" .  

![Error](https://user-images.githubusercontent.com/88758350/129134826-2400791b-7f55-4d35-9cf5-e998d9da0e46.jpg)

The guidance says "Adding a virtual port like 'cbeth0' creates a virtual ptp clock". So my questions are:
1) If the way I created the virtual network port is correct?
2) If I create a virtual network port, should I create a virtual ptp clock mannually?

By the way, if the stack can be configured to work as a gPTP slave? 

Looking forward to your feedback. Thanks.

**Comment by xl4-shiro** [comment]
Just need to run gptp2d with virtual device as the first device.
E.G.
gptp2d -d cbeth0,eth0  # this runs for the real device eth0

**Comment by bryce22** [comment]
Yes, I input the command as the example : gptp2d -d ens39:0,ens39, where ens39:0 is the virtual device and ens39 is the real device. But it can't work. 
![Error](https://user-images.githubusercontent.com/88758350/129139332-9a462b44-d836-42b7-a28a-66c6ba46b983.jpg)

I doubt the virtual network port(ens39:0) I create can't satisfy the requirement, for it may not have the virtual ptp clock. Do you have any recommendation to create a virtual network port that can satisfy the requirement?

**Comment by xl4-shiro** [comment]
the virtual device here is gptp2d created one.  When the device name starts with "cbeth", gptp2d creates a virtual network device and a virtual ptp device internally.
In your case, use 'cbeth0' instead of 'ens39:0', and run as "gptp2d -d cbeth0,ens39" should work.

**Comment by bryce22** [comment]
Ooh, I misunderstand the guidance. Now I can run the stack correctly. Thanks a lot.
